- CHANGELOG.md
- ROADMAP.md
- TODO.md
- cmd/crash-dianostics.go
Update to documentation for initial release tag.
> v0.1.0-alpha.0 initial release

- .ci/gofmt.sh
- .travis.yml
- TODO.md
- cmd/crash-dianostics.go
Initial automated build setup.
> Installing automated build

- .ci/build/build.go
- .ci/common/init.go
- .ci/deploy/travis_deploy.go
- .ci/gofmt.sh
- .ci/prebuild/gofmt_check.go
- .gitignore
- .goreleaser.yml
- .travis.yml
- buildinfo/buildinfo.go
- cmd/buildinfo.go
- cmd/crash-dianostics.go
These scripts add build and release automation.
> Build and release automation

- README.md
- TODO.md
- cmd/crash-dianostics.go
- exec/cli.go
- exec/local_exec.go
- exec/remote_exec.go
- exec/run_exec_test.go
- script/commands.go
- script/parser.go
- script/run_cmd.go
- script/run_cmd_test.go
- ssh/client.go
This PR adds support for the `RUN` directive in Diagnositics.file as explained in #4 .
This PR fixes #4 
This PR fixes #12
> Support for RUN command directive

- ROADMAP.md
- TODO.md
- docs/README.md
* Doc update
* Support several commands
* Variable expansion
* Execute commands on remote machines
* Collect and bundle machine information
> v0.1.0 release

- .github/workflows/compile-test.yaml
- .github/workflows/deploy.yaml
- README.md
Fixing badge path and other small corrections.
> Fixes for GitHub Action workflows

- README.md
- ROADMAP.md
> Adding design doc to roadmap and readme

- starlark/crashd_config.go
- starlark/crashd_config_test.go
- starlark/hostlist_provider.go
- starlark/hostlist_provider_test.go
- starlark/resources.go
- starlark/resources_test.go
- starlark/ssh_config.go
- starlark/ssh_config_test.go
- starlark/starlark_exec.go
- starlark/support.go
This PR implements the first round of provider and the resources function that can enumerate them.  
See #80
> Starlark - Implements host_list_provider and resources functions

- examples/host-list-provider.star
- examples/kind-api-objects.star
- examples/kind-capi-bootstrap.star
- examples/kube-nodes-provider.star
- examples/pod-logs.star
- examples/script-args.star
- exec/executor_test.go
- ssh/main_test.go
- starlark/capture_test.go
- starlark/copy_from_test.go
- starlark/os_builtins.go
- starlark/run_local.go
- starlark/run_test.go
- testing/setup.go
This PR adds example scripts that showcases how the new redesigned scripts work.  The examples are for fixing design and usability issues by exercising real-world scripts.
See [./examples](./examples)
> Starlark script example and tests

- exec/executor.go
- k8s/search_result.go
- starlark/crashd_config.go
- starlark/govalue.go
- starlark/govalue_test.go
- starlark/hostlist_provider.go
- starlark/kube_capture.go
- starlark/kube_config.go
- starlark/kube_get.go
- starlark/kube_nodes_provider.go
- starlark/os_builtins.go
- starlark/resources.go
- starlark/run.go
- starlark/ssh_config.go
- starlark/starlark_exec.go
- starlark/support.go
> Adds meaningful constructor name to starlark structs

- README.md
- ROADMAP.md
- TODO.md
- docs/README.md
This PR is to introduce all of the major documentation changes that comes with the redesign of the tool.  
See #127
> Document update for the version 0.3.0

- cmd/run.go
Removes the `--file` flag from the run command. Replaces it with a positional argument so that users can now execute the `run` command in the following ways:
```bash
$ crashd run --args "a=1, b=2" <file-name>
$ crashd run <file-name> --args="a=1, b=2" 
```
> Replaces named flag with positional argument

- ssh/ssh.go
- ssh/ssh_test.go
> Changes ssh command string for proxy args

- .github/workflows/deploy.yaml
- .goreleaser.yml
- go.sum
> Goreleaser generated binary name update

- cmd/run.go
- cmd/run_test.go
- util/args.go
- util/args_test.go
> Passes an empty initialized map to process args

- starlark/crashd_config.go
- starlark/kube_config.go
- util/args.go
- util/path.go
- util/path_test.go
> Allows relative paths for kubeconfig and argsfile

- docs/README.md
- starlark/capture.go
- starlark/capture_local.go
- starlark/capture_local_test.go
solve #183 capture_local should include an append flag
> add  parameter to capture_local

- cmd/buildinfo.go
- cmd/crashd.go
- cmd/run.go
Fixes #193 
Signed-off-by: Vladimir Vivien <vivienv@vmware.com>
> Fix to properly parse key=value pair from args flag

- examples/windows_capv_provider.crsh
This PR adds a working example to collect logs from a CAPV cluster running with Windows nodes
> Added windows capv example

- exec/executor.go
- exec/executor_test.go
- starlark/starlark_exec.go
This patch introduces the support for Starlark code module preload.
This feature allows scripts to reuse code in other scripts loaded
ahead of time allowing for libraries to be used by the main script.
> Support for module preload

- README.md
Signed-off-by: Benjamin Wang <wachao@vmware.com>
> fix the typo folliwng to following

- cmd/defaults.go
- cmd/run.go
- exec/executor.go
move some duplicated code into common functions
Signed-off-by: Benjamin Wang <wachao@vmware.com>
> refactor the cmd and exec package

- k8s/bastion.go
> use label for bastion discovery

- k8s/container_logger.go
- k8s/result_writer.go
- starlark/kube_capture_test.go
- testing/kindcluster.go
- testing/kindcluster_test.go
- testing/setup.go
- **Adds ability to change the print format to yaml for kube_capture**
- **Capture pod logs in parallel and ignore errors**
> Capture logs using kube_capture(what="logs") in parallel. Do not fail on error
