README.md
exec/capture_exec_test.go
script/as_cmd_test.go
script/authconfig_cmd.go
script/authconfig_cmd_test.go
script/capture_cmd.go
script/capture_cmd_test.go
script/copy_cmd.go
script/copy_cmd_test.go
script/env_cmd.go
script/env_cmd_test.go
script/from_cmd.go
script/from_cmd_test.go
script/kubecfg_cmd.go
script/kubecfg_cmd_test.go
script/output_cmd.go
script/output_cmd_test.go
script/parser.go
script/words_split.go
script/words_split_test.go
script/workdir_cmd.go
script/workdir_cmd_test.go

This PR refactors the parsing facility in the code to support quoted values i.e.:
* `DIRECTIVE "default param value"`
* `DIRECTIVE param:'aaa "bbb ccc ddd"'`
This PR fixes #11

Command string parsing with quoted value support

---

README.md
script/run_cmd.go

- `Run` command's error info currently is 'CAPTURE:'
- Modify README.md: `--loglevel debug` -> `--debug`

Change Run command's error info

---

exec/capture_exec_test.go
exec/cli.go
exec/executor_test.go
exec/remote_exec.go
exec/run_exec_test.go
script/capture_cmd.go
script/capture_cmd_test.go
script/commands.go
script/parser.go
script/run_cmd.go
script/run_cmd_test.go
script/words_split.go
script/words_split_test.go
ssh/client.go
ssh/client_test.go

This PR fixes quoting issues with DIRECTIVES which take shell commands.
The code changes can handle many scenarios including:
* `{RUN | CAPTURE} echo "Hello World!"`
* `{RUN | CAPTURE} "echo 'Hello World!'"`
* `{RUN | CAPTURE} 'echo "Hello World"'`
* `{RUN | CAPTURE} "/bin/sh -c 'date -u'"`
* `{RUN | CAPTURE} /bin/bash -c 'echo "Hello World"'`
* `{RUN | CAPTURE} shell:"/bin/bash -c" cmd:"echo 'HELLO WORLD'"`
This PR fixes #23

Fix Command Quote Handling

---

CHANGELOG.md
ROADMAP.md
TODO.md
docs/README.md
exec/env_exec.go
exec/env_exec_test.go
exec/run_exec_test.go
script/as_cmd.go
script/as_cmd_test.go
script/authconfig_cmd.go
script/authconfig_cmd_test.go
script/copy_cmd.go
script/env_cmd.go
script/env_exapand.go
script/env_expand_test.go
script/from_cmd.go
script/kubecfg_cmd.go
script/output_cmd.go
script/run_cmd.go
script/workdir_cmd.go

This PR fixes issues with variable expansion by introducing support for expansion escape as shown below:
```
ENV bazz=buzz
foo \$bar $bazz
```
Produces
```
foo $bar buzz
```
Note `\$` allows escaping of expansion.
This will allow crash-diagnostics to skip variable expansion to avoid clashing with variable names to be sent to the server.
This PR fixes #26

Support for Variable Expansion Escape

---

docs/README.md
exec/cli.go
exec/copy_exec_test.go
exec/local_exec.go
exec/remote_exec.go

This PR implements changes to support file path globbing when copying.  Now the followings will work:
```
COPY /var/log/kube-*.log
COPY $HOME/bin/*
```
This PR implements #16

Support file path globbing for COPY command

---

docs/README.md
exec/capture_exec_test.go
exec/local_exec.go
exec/remote_exec.go
exec/run_exec_test.go
exec/support.go
script/capture_cmd.go
script/capture_cmd_test.go
script/commands.go
script/run_cmd.go
script/run_cmd_test.go

This PR updates commands RUN and CAPTURE to add support param `echo` which will output command execution output to be sent to console as follows:
```
CAPTURE cmd:"echo 'HELLO WORLD'" echo:"true"
```
Related to issue #34

Support for console output for RUN and CAPTURE

---

exec/run_exec_test.go
script/authconfig_cmd_test.go
script/capture_cmd_test.go
script/copy_cmd_test.go
script/env_cmd.go
script/env_cmd_test.go
script/kubecfg_cmd_test.go
script/kubeget_cmd_test.go
script/output_cmd_test.go
script/parser.go
script/run_cmd.go
script/words_split.go
script/words_split_test.go

This PR introduces a fix for #56 . 
Now, the parser can handle
```
CAPTURE cmd:"curl host:port/service"
```

Handle commands with embedded colons

---

go.mod
go.sum
starlark/crashd_config.go
starlark/crashd_config_test.go
starlark/ssh_config.go
starlark/ssh_config_test.go
starlark/starlark_exec.go
starlark/starlark_exec_test.go
starlark/support.go

This PR is to use the Starlark language to arrive at parity with the current set of features in Crash Diagnostics.  This PR will do the followings:
* Switch to using Starlark as the configuration language
* Implement existing configuration directives as Starlark functions

Starlark - Implement Configuration Functions Impl

---

exec/executor_test.go
parser/parser_test.go
script/support_test.go
ssh/ssh_run.go
ssh/ssh_run_test.go
starlark/main_test.go
starlark/os_builtins.go
starlark/resources.go
starlark/resources_test.go
starlark/run.go
starlark/run_test.go
starlark/ssh_config.go
starlark/ssh_config_test.go
starlark/starlark_exec.go
starlark/support.go
testing/setup.go

This PR is to implement command function `run()` to support starlark script.
The following is now capable of executing (given an SSH server running on port 2424, see starlark package tests):
```python
ssh_config(username=os.username, port="2424")
resources(hosts=["127.0.0.1","localhost"])
run("echo 'Hello World!'")`
```
Or, this exaggerated example:
```python
def exec(hosts):
for host in hosts:
run(cmd="echo 'Hello World!'", resources=[host])
ssh_config(username=os.username, port="2424")
exec(resources(provider=host_list_provider(hosts=["127.0.0.1","localhost"])))
```
See #81

[WIP] Starlark - Implement command function `run()`

---

go.mod
go.sum
starlark/kube_config.go
starlark/kube_config_test.go
starlark/starlark_exec.go
starlark/starlark_exec_test.go
starlark/starlark_suite_test.go
starlark/support.go

Adds `kube_config` configuration function to allow setting the kubeconfig path for the crashd script. It overrides the global kubeconfig information present in the execution script context and can be passed to other directives explicitly. 
Examples:
```
kube_config(path="/tmp/foo/bar")
```
or 
```
cfg = kube_config(path="/tmp/foo/bar")
kube_capture(what="objects", namespaces=["default"], kube_config=cfg)
```

Adds kube_config built-in

---

ssh/ssh_run.go
ssh/ssh_run_test.go
starlark/capture.go
starlark/capture_test.go
starlark/crashd_config.go
starlark/crashd_config_test.go
starlark/main_test.go
starlark/resources_test.go
starlark/run.go
starlark/ssh_config_test.go
starlark/starlark_exec.go
starlark/support.go

This PR is to implement command function `capture()` to support which allows the following script to work
(given SSH is running on port 2424) and capture the result saved in a file at a pre-configured location:
```python
crashd_config(workdir="os.username/crashd")
ssh_config(username=os.username, port="2424")
resources(hosts=["127.0.0.1","localhost"])
capture("echo 'Hello World!'")
```
Or using additional args
```python
crashd_config(workdir="{}/crashd".format(os.home))
ssh_config(username=os.username, port="2424")
resources(hosts=["127.0.0.1","localhost"])
capture(cmd="echo 'Hello World!'", file_name="echo", desc="shows echo")
```

Starlark - Implement Command Function `capture()`

---

k8s/k8s_suite_test.go
k8s/search_result.go
k8s/search_result_test.go
starlark/kube_capture.go
starlark/kube_capture_test.go
starlark/kube_config.go
starlark/kube_config_test.go
starlark/kube_get.go
starlark/kube_get_test.go
starlark/starlark_exec.go
starlark/starlark_suite_test.go
starlark/support.go
testing/search_results.json

This patch includes the kube_get() built-in which can query and present the k8s objects as starlark values which can be usd to use in the starlark based crashd configuration file.
Example:
```
kube_cfg = kube_config(path="/tmp/kube_config")
kube_get(groups="core", namespaces=["default", "kube-system"], kube_config=kube_cfg)
```
or 
```
kube_get(groups="core", kinds=''deployments' namespaces=["default", "kube-system"])
```

Implement kube_get starlark built-in

---

.github/workflows/compile-test.yaml
ssh/client_test.go
ssh/main_test.go
ssh/scp.go
ssh/scp_test.go
ssh/ssh.go
ssh/ssh_test.go
ssh/test_support.go
starlark/capture.go
starlark/capture_test.go
starlark/copy_from.go
starlark/copy_from_test.go
starlark/main_test.go
starlark/run.go
starlark/starlark_exec.go
starlark/support.go
testing/setup.go

This PR is to implement command function `copy()` which allows the following script to work
(given SSH is running on port 2424) to copy the specified files from the remote compute resource and save them on the local machine at a pre-configured location:
```python
crashd_config(workdir="{}/crashd".format(os.home))
ssh_config(username=os.username, port="2424")
resources(hosts=["127.0.0.1","localhost"])
copy(["/var/logs/kubelet.log", "/var/logs/containers.log"])
```

Starlark - Implement Command Function `copy_from()`

---

starlark/run_local.go
starlark/run_local_test.go
starlark/starlark_exec.go
starlark/support.go

This patch implements the Go code for starlark builtin function run_local(). This
function allows Crashd script to run arbitrary command  from on the local machine.
```python
run_local("echo 'Hello World!')
```

Starlark - Implement command function `run_local()`

---

starlark/capture.go
starlark/capture_local.go
starlark/capture_local_test.go
starlark/starlark_exec.go
starlark/support.go

This patch implements the Go function that supports the `capture_local` function 
```python
capture_local(cmd="echo 'Hello World!'")
```

Starlark - Implementation of the capture_local function

---

k8s/search_params.go
starlark/kube_get.go
starlark/kube_nodes_provider.go
starlark/kube_nodes_provider_test.go
starlark/resources.go
starlark/resources_kube_nodes_provider_test.go
starlark/starlark_exec.go
starlark/support.go

This PR adds a new provider which queries a k8s cluster for the node information and returns a list of the nodes present in the said cluster.
For example:
```python
ssh_cfg = ssh_config(username="uname", key="/home/blah")
cfg = kube_config(path="/foo/bar")
res = resources(kube_nodes_provider(kube_config=cfg, ssh_config=ssh_cfg))
```
The provider also has the options of filtering the nodes based on `labels` and `names`
```python
...
res = resources(kube_nodes_provider(kube_config=cfg, names="blah", labels=["foo", "bar"]))
...
```

Adds kube_nodes_provider() starlark built-in

---

ssh/scp.go
starlark/capture.go
starlark/capture_local.go
starlark/copy_from.go
starlark/crashd_config.go
starlark/crashd_config_test.go
starlark/hostlist_provider.go
starlark/hostlist_provider_test.go
starlark/kube_config.go
starlark/resources.go
starlark/resources_test.go
starlark/run.go
starlark/ssh_config.go
starlark/ssh_config_test.go
starlark/starlark_exec.go
starlark/starlark_exec_test.go

This PR updates the code to use `starlark.UnpackArgs` for better handling of script arguments when executing Go built-in starlark functions.
See #103

Starlark - Better argument handling with `starlark.UnpackArgs`

---

starlark/archive.go
starlark/archive_test.go
starlark/crashd_config_test.go
starlark/starlark_exec.go
starlark/support.go

This PR implements #110 
The archive function allows script developers to bundle arbitrary directories to create compressed bundles (tar.gz)

Implementation of the archive script function

---

starlark/kube_capture.go
starlark/kube_capture_test.go
starlark/kube_config.go
starlark/kube_get.go
starlark/kube_get_test.go
starlark/kube_nodes_provider.go

Use the starlark provided UnpackArgs function to fetch arguments for the `kube_get`, `kube_capture` and `kube_nodes_provider` directives.

Unpacking kube directive arguments via Starlark library function

---

examples/capv_provider.star
examples/kind-api-objects.star
examples/kind-capi-bootstrap.star
examples/pod-logs.star
examples/script-args.star
starlark/capture_test.go
starlark/copy_from_test.go
starlark/hostlist_provider_test.go
starlark/kube_capture_test.go
starlark/kube_config.go
starlark/kube_config_test.go
starlark/kube_get_test.go
starlark/kube_nodes_provider_test.go
starlark/resources.go
starlark/resources_kube_nodes_provider_test.go
starlark/resources_test.go
starlark/set_as_default.go
starlark/set_as_default_test.go
starlark/ssh_config.go
starlark/ssh_config_test.go
starlark/starlark_exec.go
starlark/support.go

This patch introduces a new starlark directive called as `set_as_default` which can be used to set the default values of one of the three types:
- kube_config
- ssh_config
- resources
Previously, on each call of kube_config, ssh_config or resources, the resulting value was set in the local starlark thread and available inside the script. This patch removes the need for this default behavior. Instead, the script developer needs to make a choice to call the set_as_default directive with the value that needs to be stored in the thread.
Example:
```python
cfg = kube_config(path="/blah/foo/bar")
set_as_default(kube_config = cfg)
```
OR
```python
set_as_default(ssh_config = ssh_config(username="uname", private_key_path="/home/foo/.ssh/id_rsa_custom")
```

Adds the set_as_default directive

---

starlark/kube_capture.go
starlark/kube_config.go
starlark/kube_get.go
starlark/kube_nodes_provider.go

This patch fixes the function name input to the starlark.UnpackArgs() library function call which was set incorrectly for some of the kube functions.

Fix UnpackArgs inputs for kube functions

---

cmd/run.go
examples/capa_provider.star
go.mod
go.sum
k8s/bastion.go
k8s/cluster.go
k8s/kube_config.go
provider/kube_config.go
starlark/capa_provider.go
starlark/capv_provider.go
starlark/kube_config.go
starlark/ssh_config.go
starlark/starlark_exec.go
starlark/support.go

Adds a new resource provider which can be used to list out resources for a CAPA managed workload cluster.
This also includes updating the capv_provider to include the workspace for the queried workload cluster.
Example:
```python
wc_provider=capa_provider(
workload_cluster="calico-aws",
namespace="abcdef",
ssh_config=ssh_conf,
mgmt_kube_config=kube_config(path="/kube/config")
)
nodes = resources(provider=wc_provider)
capture(cmd="sudo df -i", resources=nodes)
capture(cmd="sudo crictl info", resources=nodes)
mgmt_nodes = resources(provider=capa_provider(
namespace="blah",
ssh_config=ssh_conf,
mgmt_kube_config=kube_config(path="/kube/config")
))
capture(cmd="ls -alh", resources=mgmt_nodes)
```

Includes a new provider for CAPA managed objects

---

cmd/crash-dianostics.go
docs/README.md
starlark/capa_provider.go
starlark/capv_provider.go
starlark/kube_config.go
starlark/kube_config_test.go

The new help information for the CLI now reflects the binary name as `crashd`.
```bash
$ ./crashd --help
crashd collects diagnostics from an unresponsive Kubernetes cluster
Usage:
crashd [command]
Available Commands:
help        Help about any command
run         Executes a diagnostics script file
version     prints the crash-diagnostics version
Flags:
--debug     sets log level to debug
-h, --help      help for crashd
--version   version for crashd
Use "crashd [command] --help" for more information about a command.
```
This PR also updates the `capa_provider` and `capv_provider` directives to return the k8s configuration under the key name `kube_config`. It also updates the docs with new parameter names.

Updates the CLI name to crashd

---

.github/workflows/compile-test.yaml
examples/kube-nodes-provider.crsh
ssh/scp_test.go
ssh/ssh_test.go
ssh/test_support.go
starlark/capture_test.go
starlark/copy_from_test.go
starlark/main_test.go
starlark/run_test.go
testing/setup.go
testing/sshserver.go

This patch reverts the logic to use a custom keypair for testing purposes.

Reverts using custom ssh keypair for tests

---

README.md

The `--args` flag for the `run` command requires a comma separated list of key=value pairs as an input.

Fixes example for the args flag of the run command

---

cmd/cmd_suite_test.go
cmd/run.go
cmd/run_test.go
util/args.go
util/args_test.go
util/util_suite_test.go

Instead of passing a number of key=value arguments via the command line, the script executor can now pass a path to a file containing key-value pairs which can be passed to the diagnostics file.
```bash
$ cat /tmp/script.args
foo=bar
blah = bleep
$ crash run diagnsotics.crsh --args-file /tmp/script.args
```
The supplied args file is valid if it follows the format:
1. a line contains a single key-value pair separated by `=` sign (eg: foo=bar|foo =bar|foo= bar|foo = bar)
1. a line can either contain a key-value pair in the above format or a comment statement starting with `#`
Empty lines are valid content. Any line not containing the following format will result in a warning message appear on the screen, and would be ignored.
```bash
$ cat /tmp/script.args
foo=bar
bloop blah
$ crash run …
```

Adds `--args-file` flag to crashd run command

---

.github/workflows/compile-test.yaml
exec/executor.go
go.mod
ssh/agent.go
ssh/agent_test.go
ssh/scp.go
ssh/scp_test.go
ssh/ssh.go
ssh/ssh_test.go
ssh/test_support.go
starlark/capa_provider.go
starlark/capture.go
starlark/copy_from.go
starlark/crashd_config.go
starlark/crashd_config_test.go
starlark/resources.go
starlark/run.go
starlark/ssh_config.go
starlark/starlark_exec.go
starlark/support.go

Adds the ability to start/stop an instance of the `ssh-agent` and add/remove keys to/from this `ssh-agent` instance. This instance of the agent is alive only for the scope of the execution of the Starlark script. Thus, the default instance of the ssh-agent in use by the current shell remains unchanged.
This patch adds a new Boolean parameter to the `crashd_config()` directive named as `use_ssh_agent`. Whenever this is set in the script, crashd starts a new instance of the `ssh-agent` and all the following ssh keys mentioned in the script get added to this instance of the agent. All following ssh/scp operations leverage this ssh-agent for remote connections.
Example:
```python
crashd_config(use_ssh_agent=True)
...
ssh_config(path="/foo/bar")
provider=host_list_provider(hosts=["localhost", …
```

Adds support for passphrase protected ssh key

---

cmd/crash-dianostics.go
cmd/defaults.go
cmd/run.go
cmd/run_test.go

Create a `.crashd` dir under the `$HOME` directory which houses the fallback argsfile which will be used if no `--args-file` is passed to the `run` command.
fixes: #166

Adds .crashd directory when running the program

---

starlark/prog_avail_local.go
starlark/prog_avail_local_test.go
starlark/starlark_exec.go
starlark/support.go

This PR adds `prog_avail_local` support for crashd scripts.
`prog_avail_local` check if a program is available on host machine.
Example script:
```
def run():
prog="echo"
path = prog_avail_local(prog=prog)
if path == "":
print("prog '{}' is not available".format(prog))
else:
print("prog '{}' is available at '{}'".format(prog, path))
run()
```

add prog_avail_local function

---

ssh/agent.go
ssh/scp.go
ssh/scp_test.go
ssh/test_support.go
starlark/copy_to.go
starlark/copy_to_test.go
starlark/run_test.go
starlark/starlark_exec.go
starlark/support.go

This patch, overall, implements the new `copy_to()` Crashd script command.
It also includes the following updates:
* package ssh to support CopyFrom and CopyTo
* New tests in ssh package
* Addition of copyToFunc Starlark Go function
* Tests for copyToFunc
Fixes #150

Implements support for copy_to() starlark function

---

k8s/nodes.go

This PR corrects an issue when trying to filtering for capv or capa providers the labels get input to the k8s search as names
```
provider = capv_provider(
workload_cluster=cluster_name,
namespace=ns,
ssh_config=ssh_cfg,
mgmt_kube_config=kube_cfg,
labels=["kubernetes.io/os=linux"]
)
Search filters groups:[core]; kinds:[nodes]; namespaces:[]; versions:[]; names:[kubernetes.io/os=linux]; labels:[] containers:[]
```
This is because of a mismatch in the order of names and labels when calling this function in the providers

Corrected order of GetNodeAddresses inputs to match providers

---

starlark/run_local.go

This patch changes built-in function run_local to return an error string,
instead of error out, at runtime. Previously, the function would cause
the script to crash by erroring out completely.
Fixes #197

Modify run_local to return error (#197)

---

docs/README.md
starlark/log.go
starlark/log_test.go
starlark/starlark_exec.go
starlark/support.go

This patch implements a log function that can be used in starlark scripts.
The implementation uses the stdlib log package to print log information.
Signed-off-by: Vladimir Vivien <vivienv@vmware.com>

Implement starlark log script function

---

starlark/log.go
starlark/log_test.go
starlark/starlark_exec.go

The previous patch missed adding the log function as a predeclared
starlark function. So this caused a bug when executing scripts that
uses the log function.
Signed-off-by: Vladimir Vivien <vivienv@vmware.com>

Script log function fix

---

docs/README.md
k8s/client.go
k8s/client_test.go
starlark/capa_provider.go
starlark/capv_provider.go
starlark/kube_capture.go
starlark/kube_capture_test.go
starlark/kube_config.go
starlark/kube_config_test.go
starlark/kube_get.go
starlark/kube_get_test.go
starlark/kube_nodes_provider.go
testing/setup.go

This patch introduces support for cluster context name when
declaring kubeernetes configuration using the kube_config starlark script
function. Now, command functions such as kube_get and kube_capture
can create connection to the API server using the local kubectl CLI
cluster context name.
Fixes #122

Support for cluster context name in kube_config function (#122)

---

go.mod
go.sum
starlark/capture_local.go
starlark/capture_local_test.go

This patch modifies script command capture_local to avoid crashing
the script execution upon error. This fix captures the command error
and writes it in the file and continues the script execution.
Fixes #219

Capture local error return

---

cmd/crashd.go
cmd/defaults.go
logging/cli.go
logging/file.go
starlark/archive.go
starlark/archive_test.go
starlark/log.go
starlark/starlark_exec.go
starlark/support.go

- regardless of CLI verbosity, log at trace level into a file and persist into result archive
- always include the script that was run in the result archive
- args were not persisted since they may include auth information
- the new features are able to be disabled; logging to file via a flag, archive options via new
keyword args.
Signed-off-by: John Schnake <jschnake@vmware.com>

Add script that was run and logs into archive by default

---

cmd/run_test.go
k8s/kube_config.go
k8s/search_result_test.go
ssh/scp_test.go
starlark/copy_from_test.go
starlark/kube_capture_test.go
util/args_test.go

The `io/ioutil` package has already been deprecated starting from golang 1.16, please refer to https://go.dev/doc/go1.16#ioutil
Signed-off-by: Benjamin Wang <wachao@vmware.com>

cleanup the deprecated io/ioutil

---

docs/README.md
k8s/object_writer.go
k8s/result_writer.go
starlark/kube_capture.go
starlark/kube_capture_test.go

- By specifying output_mode=multiple-files one can force kube_capture to gather k8s resources in separate files as opposed to storing them in a single json/yaml file

Adds new parameter `output_mode` to kube_capture
